SilverStripe\Forms\FieldList:
  extensions:
    - UncleCheese\ZenFields\ZenFields
SilverStripe\Forms\FieldGroup:
  extensions:
    - UncleCheese\ZenFields\ZenFieldGroup
SilverStripe\Forms\FormField:
  extensions:
    - UncleCheese\ZenFields\ZenFormField
SilverStripe\Forms\GridField\GridField:
  extensions:
    - UncleCheese\ZenFields\ZenGridField
SilverStripe\AssetAdmin\Forms\UploadField:
  extensions:
    - UncleCheese\ZenFields\ZenUploadField
UncleCheese\ZenFields\ZenFields:
  gridfield_sortable_component_classes:
    - Symbiote\GridFieldExtensions\GridFieldOrderableRows
